using System.Collections.Generic;

namespace RandomMagicConversion;

internal enum AppLanguage
{
    French,
    English,
    Chinese
}

internal static class UiText
{
    private static readonly Dictionary<string, string> French = new()
    {
        ["AppTitle"] = "✨ SIDERAL : Sorcelleries, Incantations et Disciplines Ésotériques Réassignés Aléatoirement aux Loots 💫",
        ["Automatic"] = "Automatique",
        ["Paths"] = "Chemins",
        ["Options"] = "Options",
        ["Log"] = "Journal",
        ["InputRegulation"] = "Regulation source",
        ["OutputRegulation"] = "Regulation généré",
        ["GameExecutable"] = "Exécutable du jeu",
        ["RandomizerExecutable"] = "Exécutable du Randomizer",
        ["Browse"] = "Parcourir...",
        ["Profile"] = "Profil",
        ["ProfileHelp"] = "Compatible Randomizer : prévu pour être utilisé avec le mod Randomizer. Autonome : prévu pour utiliser ce mod seul.",
        ["MagicType"] = "Type de magie",
        ["MagicTypeHelp"] = "Choisit si les remplacements utilisent les sorcelleries, les incantations, ou les deux.",
        ["Seed"] = "Seed",
        ["SeedHelp"] = "Laisser vide pour générer un nouveau Seed automatiquement. Renseigner un nombre permet de refaire exactement la même génération.",
        ["Language"] = "Langue",
        ["LanguageHelp"] = "Change la langue de l'interface.",
        ["Option"] = "Option",
        ["OptionDescription"] = "Description des options",
        ["ProfileRandomizer"] = "Compatible Randomizer",
        ["ProfileStandalone"] = "Autonome",
        ["PoolBoth"] = "Sorcelleries et incantations",
        ["PoolSorcery"] = "Sorcelleries uniquement",
        ["PoolIncantation"] = "Incantations uniquement",
        ["ShieldOption"] = "Boucliers -> Bâtons / Sceaux",
        ["ShopOption"] = "Armes de boutiques -> Magie",
        ["MapLootOption"] = "Armes trouvées sur la carte -> Magie",
        ["BossOption"] = "Récompenses de boss -> Magie",
        ["EnemyLotOption"] = "Armes récupérées sur les ennemis -> Magie",
        ["FarmableEnemyLootOption"] = "Bloquer les loots ennemis farmables",
        ["AshOption"] = "Cendres de guerre -> Magie",
        ["StartingClassOption"] = "Armes de départ des classes -> Magie",
        ["TextOption"] = "Transformer les textes des objets de base par les objets transformés",
        ["StandaloneNoRequirementsOption"] = "Retirer les prérequis de stats (Autonome)",
        ["HelpShield"] = "Boucliers -> Bâtons / Sceaux : Cette option permet la transformation des boucliers en bâtons et sceaux. Décocher si vous souhaitez laisser les boucliers en jeu. Note : il est possible d'effectuer des parades avec les sceaux et les bâtons.",
        ["HelpShop"] = "Armes de boutiques -> Magie : Permet de transformer toutes les armes se trouvant dans les boutiques des PNJ en sorcelleries et incantations. Cela ne concerne pas les armes liées aux souvenirs de boss. Voir Récompenses de boss.",
        ["HelpMapLoot"] = "Armes trouvées sur la carte -> Magie : Permet de transformer toutes les armes se trouvant dans le monde ouvert en sorcelleries et incantations.",
        ["HelpBoss"] = "Récompenses de boss -> Magie : Permet de transformer les armes liées aux souvenirs de boss en sorcelleries et incantations.",
        ["HelpEnemyLot"] = "Armes récupérées sur les ennemis -> Magie : Permet de transformer les armes récupérées sur les ennemis en sorcelleries et incantations.",
        ["HelpFarmableEnemyLoot"] = "Bloquer les loots ennemis farmables : Permet de ne plus récupérer tous les objets récupérables par les ennemis. Ceci permet de bloquer les objets récupérables après randomisation sur les ennemis.",
        ["HelpAsh"] = "Cendres de guerre -> Magie : Permet de transformer les cendres de guerre en sorcelleries et incantations.",
        ["HelpStartingClass"] = "Armes de départ des classes -> Magie : Permet de transformer les armes de départ des classes en sorcelleries et incantations. ATTENTION : Si cette option est cochée, il est IMPÉRATIF de ne pas randomiser les armes de départ des classes via le mod Randomizer. Cela entraînera une erreur lors de la génération du Seed si tel est le cas.",
        ["HelpText"] = "Transformer les textes des objets de base par les objets transformés : Permet de transformer les textes des objets transformés.",
        ["HelpStandaloneNoRequirements"] = "Retirer les prérequis de stats (Autonome) : En profil Autonome, met à 0 les prérequis de stats des bâtons, sceaux, sorcelleries et incantations.",
        ["RegulationFilter"] = "regulation (*.bin)",
        ["ExecutableFilter"] = "Exécutables (*.exe)",
        ["AllFilesFilter"] = "Tous les fichiers (*.*)",
        ["BrowseError"] = "Impossible d'ouvrir la fenêtre de sélection.\r\n\r\n{0}",
        ["Generate"] = "Générer regulation.bin",
        ["LaunchGame"] = "Lancer le jeu",
        ["LaunchRandomizer"] = "Lancer le mod Randomizer",
        ["GenerationStarted"] = "Génération lancée...",
        ["GenerationFinishedLog"] = "Terminé. Seed : {0}",
        ["GeneratedFileLog"] = "Fichier généré : {0}",
        ["GenerationDoneMessage"] = "Génération terminée.\r\n\r\nSeed : {0}\r\nSortie : {1}",
        ["GenerationErrorLog"] = "Erreur : {0}",
        ["GenerationErrorTitle"] = "Erreur de génération",
        ["StandaloneOnlyLaunch"] = "Le lancement via Mod Engine est disponible uniquement avec le profil Autonome.",
        ["GamePathRequired"] = "Renseignez le chemin de eldenring.exe avant de lancer Elden Ring.",
        ["GameFolderInvalid"] = "Le chemin de eldenring.exe ne permet pas de retrouver le dossier Game.",
        ["GeneratedRegulationMissing"] = "Le regulation.bin généré est introuvable. Lancez d'abord la génération.",
        ["OutputFolderMissing"] = "Impossible de retrouver le dossier Output du regulation.bin généré.",
        ["ModEngineFolderMissing"] = "Impossible de retrouver le dossier du launcher Mod Engine.",
        ["ModEngineConfigLog"] = "Config Mod Engine SIDERAL : {0}",
        ["InjectedModFolderLog"] = "Dossier de mod injecté : {0}",
        ["GameExecutableLog"] = "Exécutable du jeu renseigné : {0}",
        ["ModEngineLaunchRequested"] = "Lancement via Mod Engine demandé.",
        ["LaunchErrorLog"] = "Erreur lancement : {0}",
        ["LaunchErrorTitle"] = "Erreur de lancement",
        ["RandomizerOnlyLaunch"] = "Le lancement du Randomizer est disponible uniquement avec le profil Compatible Randomizer.",
        ["RandomizerPathRequired"] = "Renseignez le chemin de EldenRingRandomizer.exe avant de lancer le Randomizer.",
        ["RandomizerMissing"] = "EldenRingRandomizer.exe est introuvable. Vérifiez le chemin renseigné.",
        ["RandomizerFolderInvalid"] = "Le chemin de EldenRingRandomizer.exe ne permet pas de retrouver son dossier.",
        ["RandomizerLaunchLog"] = "Lancement du Randomizer demandé : {0}",
        ["RandomizerLaunchErrorLog"] = "Erreur lancement Randomizer : {0}",
        ["RandomizerLaunchErrorTitle"] = "Erreur de lancement Randomizer",
        ["SeedInvalid"] = "Le Seed doit être un entier valide.",
        ["ModEngineNotFound"] = "modengine2_launcher.exe est introuvable. Téléchargez Mod Engine 2 depuis https://github.com/soulsmods/ModEngine2/releases, puis sélectionnez-le manuellement.",
        ["ModEngineDialogTitle"] = "Sélectionner modengine2_launcher.exe"
    };

    private static readonly Dictionary<string, string> English = new()
    {
        ["AppTitle"] = "✨ SIDERAL: Sorceries, Incantations, and Esoteric Disciplines Randomly Reassigned to Loots 💫",
        ["Automatic"] = "Automatic",
        ["Paths"] = "Paths",
        ["Options"] = "Options",
        ["Log"] = "Log",
        ["InputRegulation"] = "Source regulation",
        ["OutputRegulation"] = "Generated regulation",
        ["GameExecutable"] = "Game executable",
        ["RandomizerExecutable"] = "Randomizer executable",
        ["Browse"] = "Browse...",
        ["Profile"] = "Profile",
        ["ProfileHelp"] = "Randomizer Compatible: designed to be used with the Randomizer mod. Standalone: designed to use SIDERAL by itself.",
        ["MagicType"] = "Magic type",
        ["MagicTypeHelp"] = "Chooses whether replacements use sorceries, incantations, or both.",
        ["Seed"] = "Seed",
        ["SeedHelp"] = "Leave empty to generate a new Seed automatically. Enter a number to reproduce the exact same generation.",
        ["Language"] = "Language",
        ["LanguageHelp"] = "Changes the interface language.",
        ["Option"] = "Option",
        ["OptionDescription"] = "Option descriptions",
        ["ProfileRandomizer"] = "Randomizer Compatible",
        ["ProfileStandalone"] = "Standalone",
        ["PoolBoth"] = "Sorceries and incantations",
        ["PoolSorcery"] = "Sorceries only",
        ["PoolIncantation"] = "Incantations only",
        ["ShieldOption"] = "Shields -> Staffs / Seals",
        ["ShopOption"] = "Shop weapons -> Magic",
        ["MapLootOption"] = "Map loot weapons -> Magic",
        ["BossOption"] = "Boss rewards -> Magic",
        ["EnemyLotOption"] = "Enemy drop weapons -> Magic",
        ["FarmableEnemyLootOption"] = "Block farmable enemy loot",
        ["AshOption"] = "Ashes of War -> Magic",
        ["StartingClassOption"] = "Starting class weapons -> Magic",
        ["TextOption"] = "Replace base item texts with transformed item texts",
        ["StandaloneNoRequirementsOption"] = "Remove stat requirements (Standalone)",
        ["HelpShield"] = "Shields -> Staffs / Seals: transforms shields into staffs and seals. Disable it if you want to keep shields in the game. Note: seals and staffs can parry.",
        ["HelpShop"] = "Shop weapons -> Magic: transforms weapons sold by NPC shops into sorceries and incantations. This does not affect boss remembrance weapons. See Boss rewards.",
        ["HelpMapLoot"] = "Map loot weapons -> Magic: transforms weapons found in the open world into sorceries and incantations.",
        ["HelpBoss"] = "Boss rewards -> Magic: transforms boss remembrance weapons into sorceries and incantations.",
        ["HelpEnemyLot"] = "Enemy drop weapons -> Magic: transforms weapons dropped by enemies into sorceries and incantations.",
        ["HelpFarmableEnemyLoot"] = "Block farmable enemy loot: prevents enemies from dropping farmable items. This blocks items that remain farmable after enemy randomization.",
        ["HelpAsh"] = "Ashes of War -> Magic: transforms Ashes of War into sorceries and incantations.",
        ["HelpStartingClass"] = "Starting class weapons -> Magic: transforms starting class weapons into sorceries and incantations. WARNING: if this option is enabled, do not randomize starting class weapons in the Randomizer mod. Doing so will cause an error when generating the Seed.",
        ["HelpText"] = "Replace base item texts with transformed item texts: updates the text of transformed items.",
        ["HelpStandaloneNoRequirements"] = "Remove stat requirements (Standalone): in the Standalone profile, sets staff, seal, sorcery, and incantation stat requirements to 0.",
        ["RegulationFilter"] = "regulation (*.bin)",
        ["ExecutableFilter"] = "Executables (*.exe)",
        ["AllFilesFilter"] = "All files (*.*)",
        ["BrowseError"] = "Could not open the selection window.\r\n\r\n{0}",
        ["Generate"] = "Generate regulation.bin",
        ["LaunchGame"] = "Launch game",
        ["LaunchRandomizer"] = "Launch Randomizer mod",
        ["GenerationStarted"] = "Generation started...",
        ["GenerationFinishedLog"] = "Done. Seed: {0}",
        ["GeneratedFileLog"] = "Generated file: {0}",
        ["GenerationDoneMessage"] = "Generation complete.\r\n\r\nSeed: {0}\r\nOutput: {1}",
        ["GenerationErrorLog"] = "Error: {0}",
        ["GenerationErrorTitle"] = "Generation error",
        ["StandaloneOnlyLaunch"] = "Launching through Mod Engine is only available with the Standalone profile.",
        ["GamePathRequired"] = "Enter the path to eldenring.exe before launching Elden Ring.",
        ["GameFolderInvalid"] = "The eldenring.exe path does not allow SIDERAL to find the Game folder.",
        ["GeneratedRegulationMissing"] = "The generated regulation.bin could not be found. Generate it first.",
        ["OutputFolderMissing"] = "Could not find the Output folder for the generated regulation.bin.",
        ["ModEngineFolderMissing"] = "Could not find the Mod Engine launcher folder.",
        ["ModEngineConfigLog"] = "SIDERAL Mod Engine config: {0}",
        ["InjectedModFolderLog"] = "Injected mod folder: {0}",
        ["GameExecutableLog"] = "Game executable path: {0}",
        ["ModEngineLaunchRequested"] = "Launch through Mod Engine requested.",
        ["LaunchErrorLog"] = "Launch error: {0}",
        ["LaunchErrorTitle"] = "Launch error",
        ["RandomizerOnlyLaunch"] = "Launching the Randomizer is only available with the Randomizer Compatible profile.",
        ["RandomizerPathRequired"] = "Enter the path to EldenRingRandomizer.exe before launching the Randomizer.",
        ["RandomizerMissing"] = "EldenRingRandomizer.exe could not be found. Check the selected path.",
        ["RandomizerFolderInvalid"] = "The EldenRingRandomizer.exe path does not allow SIDERAL to find its folder.",
        ["RandomizerLaunchLog"] = "Randomizer launch requested: {0}",
        ["RandomizerLaunchErrorLog"] = "Randomizer launch error: {0}",
        ["RandomizerLaunchErrorTitle"] = "Randomizer launch error",
        ["SeedInvalid"] = "The Seed must be a valid integer.",
        ["ModEngineNotFound"] = "modengine2_launcher.exe could not be found. Download Mod Engine 2 from https://github.com/soulsmods/ModEngine2/releases, then select it manually.",
        ["ModEngineDialogTitle"] = "Select modengine2_launcher.exe"
    };

    private static readonly Dictionary<string, string> Chinese = new()
    {
        ["AppTitle"] = "✨ SIDERAL：魔法、祷告与秘术，随机重分配至战利品 💫",
        ["Automatic"] = "自动",
        ["Paths"] = "路径",
        ["Options"] = "选项",
        ["Log"] = "日志",
        ["InputRegulation"] = "源 regulation",
        ["OutputRegulation"] = "生成的 regulation",
        ["GameExecutable"] = "游戏可执行文件",
        ["RandomizerExecutable"] = "Randomizer 可执行文件",
        ["Browse"] = "浏览...",
        ["Profile"] = "配置",
        ["ProfileHelp"] = "兼容 Randomizer：用于配合 Randomizer 模组。独立模式：用于单独使用 SIDERAL。",
        ["MagicType"] = "魔法类型",
        ["MagicTypeHelp"] = "选择替换结果使用魔法、祷告，或两者都使用。",
        ["Seed"] = "Seed",
        ["SeedHelp"] = "留空会自动生成新的 Seed。输入数字可以复现完全相同的生成结果。",
        ["Language"] = "语言",
        ["LanguageHelp"] = "切换界面语言。",
        ["Option"] = "选项",
        ["OptionDescription"] = "选项说明",
        ["ProfileRandomizer"] = "兼容 Randomizer",
        ["ProfileStandalone"] = "独立模式",
        ["PoolBoth"] = "魔法与祷告",
        ["PoolSorcery"] = "仅魔法",
        ["PoolIncantation"] = "仅祷告",
        ["ShieldOption"] = "盾牌 -> 法杖 / 圣印",
        ["ShopOption"] = "商店武器 -> 魔法",
        ["MapLootOption"] = "地图拾取武器 -> 魔法",
        ["BossOption"] = "Boss 奖励 -> 魔法",
        ["EnemyLotOption"] = "敌人掉落武器 -> 魔法",
        ["FarmableEnemyLootOption"] = "阻止可刷敌人掉落",
        ["AshOption"] = "战灰 -> 魔法",
        ["StartingClassOption"] = "初始职业武器 -> 魔法",
        ["TextOption"] = "将基础物品文本替换为转换后的物品文本",
        ["StandaloneNoRequirementsOption"] = "移除属性需求（独立模式）",
        ["HelpShield"] = "盾牌 -> 法杖 / 圣印：将盾牌转换为法杖和圣印。如果你想保留游戏中的盾牌，请取消勾选。注意：圣印和法杖可以进行弹反。",
        ["HelpShop"] = "商店武器 -> 魔法：将 NPC 商店出售的武器转换为魔法和祷告。不包括 Boss 追忆武器。请查看 Boss 奖励选项。",
        ["HelpMapLoot"] = "地图拾取武器 -> 魔法：将开放世界中可拾取的武器转换为魔法和祷告。",
        ["HelpBoss"] = "Boss 奖励 -> 魔法：将 Boss 追忆武器转换为魔法和祷告。",
        ["HelpEnemyLot"] = "敌人掉落武器 -> 魔法：将敌人掉落的武器转换为魔法和祷告。",
        ["HelpFarmableEnemyLoot"] = "阻止可刷敌人掉落：阻止敌人掉落可反复刷取的物品。这可以屏蔽敌人随机化后仍可刷取的物品。",
        ["HelpAsh"] = "战灰 -> 魔法：将战灰转换为魔法和祷告。",
        ["HelpStartingClass"] = "初始职业武器 -> 魔法：将初始职业武器转换为魔法和祷告。警告：如果启用此选项，请不要在 Randomizer 模组中随机化初始职业武器，否则生成 Seed 时会出错。",
        ["HelpText"] = "将基础物品文本替换为转换后的物品文本：更新已转换物品的文本。",
        ["HelpStandaloneNoRequirements"] = "移除属性需求（独立模式）：在独立模式下，将法杖、圣印、魔法和祷告的属性需求设为 0。",
        ["RegulationFilter"] = "regulation (*.bin)",
        ["ExecutableFilter"] = "可执行文件 (*.exe)",
        ["AllFilesFilter"] = "所有文件 (*.*)",
        ["BrowseError"] = "无法打开选择窗口。\r\n\r\n{0}",
        ["Generate"] = "生成 regulation.bin",
        ["LaunchGame"] = "启动游戏",
        ["LaunchRandomizer"] = "启动 Randomizer 模组",
        ["GenerationStarted"] = "开始生成...",
        ["GenerationFinishedLog"] = "完成。Seed：{0}",
        ["GeneratedFileLog"] = "已生成文件：{0}",
        ["GenerationDoneMessage"] = "生成完成。\r\n\r\nSeed：{0}\r\n输出：{1}",
        ["GenerationErrorLog"] = "错误：{0}",
        ["GenerationErrorTitle"] = "生成错误",
        ["StandaloneOnlyLaunch"] = "通过 Mod Engine 启动仅适用于独立模式配置。",
        ["GamePathRequired"] = "启动 Elden Ring 前，请填写 eldenring.exe 的路径。",
        ["GameFolderInvalid"] = "eldenring.exe 的路径无法定位 Game 文件夹。",
        ["GeneratedRegulationMissing"] = "找不到生成的 regulation.bin。请先生成文件。",
        ["OutputFolderMissing"] = "无法找到生成的 regulation.bin 所在的 Output 文件夹。",
        ["ModEngineFolderMissing"] = "无法找到 Mod Engine 启动器文件夹。",
        ["ModEngineConfigLog"] = "SIDERAL Mod Engine 配置：{0}",
        ["InjectedModFolderLog"] = "注入的模组文件夹：{0}",
        ["GameExecutableLog"] = "游戏可执行文件路径：{0}",
        ["ModEngineLaunchRequested"] = "已请求通过 Mod Engine 启动。",
        ["LaunchErrorLog"] = "启动错误：{0}",
        ["LaunchErrorTitle"] = "启动错误",
        ["RandomizerOnlyLaunch"] = "启动 Randomizer 仅适用于兼容 Randomizer 配置。",
        ["RandomizerPathRequired"] = "启动 Randomizer 前，请填写 EldenRingRandomizer.exe 的路径。",
        ["RandomizerMissing"] = "找不到 EldenRingRandomizer.exe。请检查所选路径。",
        ["RandomizerFolderInvalid"] = "EldenRingRandomizer.exe 的路径无法定位其文件夹。",
        ["RandomizerLaunchLog"] = "已请求启动 Randomizer：{0}",
        ["RandomizerLaunchErrorLog"] = "Randomizer 启动错误：{0}",
        ["RandomizerLaunchErrorTitle"] = "Randomizer 启动错误",
        ["SeedInvalid"] = "Seed 必须是有效整数。",
        ["ModEngineNotFound"] = "找不到 modengine2_launcher.exe。请从 https://github.com/soulsmods/ModEngine2/releases 下载 Mod Engine 2，然后手动选择该文件。",
        ["ModEngineDialogTitle"] = "选择 modengine2_launcher.exe"
    };

    public static string Get(AppLanguage language, string key)
    {
        Dictionary<string, string> source = language switch
        {
            AppLanguage.English => English,
            AppLanguage.Chinese => Chinese,
            _ => French
        };

        return source.TryGetValue(key, out string value)
            ? value
            : French.TryGetValue(key, out string fallback)
                ? fallback
                : key;
    }
}
